# Put the path to directory with input data and the path to directory where the clean files will be created
path_input:        /home/input/capes/
path_output:       /home/output/capes/
database_ids:      /home/output/intermediario/dac_comvest_ids.csv